### ISSUE TITLE
feat: Cortex has verbose logs `-v`

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#1015]
**Problem**

Cortex sometimes fails without any user side information. 
Let's err on the side of verbose logs

**Success Criteria**

1. Whenever users run commands `cortex CMD -v`, we log everything
2. By default, we can stick with the current level of logging.

**Additional context**

**Comment by ux-han** [comment]
duplicated with https://github.com/janhq/jan/issues/1989
