### ISSUE TITLE
I still got 'Illegal instruction' bug under cuda with ubuntu 22.04.

### ISSUE THREAD

**Issue by lovehunter9** [janhq/cortex#317]
I still got this bug.
<img width="1142" alt="image" src="https://github.com/janhq/nitro/assets/39935488/5739e99e-eca4-4614-9e1f-f6af2a52ba23">

_Originally posted by @lovehunter9 in https://github.com/janhq/nitro/issues/273#issuecomment-1878192726_

**Comment by 0xSage** [comment]
closing no reply
