### ISSUE TITLE
feat: Support for Nitro with llama.cpp vulkan backend on Mac

### ISSUE THREAD

**Issue by hiro-v** [janhq/cortex#476]
**Problem**
- Context: https://discord.com/channels/1107178041848909847/1222681742712897609
- User with Mac Intel and AMD Radeon wants to use Vulkan to accelerate models

**Success Criteria**
- Nitro build to support this

**Additional context**

**Comment by 0xSage** [comment]
@hiro-v is this issue still relevant? pls close if not 🙏
