### ISSUE TITLE
bug: slow response after terminate the conversation 

### ISSUE THREAD

**Issue by cht132** [janhq/cortex#493]
**Describe the bug**
close / terminate the conversation of the streaming output will introduce slow performance of new chat

**To Reproduce**
1. start the check enable with stream
2. when nitro streaming text output, close the chat from client
3. in server log, it displayed "Task completed, release it - llamaCPP.cc:416"
4. start the new chat, it will be slow response until restart nitro from server

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Comment by louis-jan** [comment]
Sus: The streaming task is still going on in the background. Hopefully the new Cortex revamp addressed this @vansangpfiev

**Comment by louis-jan** [comment]
To test with new Cortex, I guess that is about caching stuff or so, it's also depend on conversation length, remaining resources. It's a bit unclear how to measure. Open back if you get a new clue or information @cht132 @vansangpfiev
