### ISSUE TITLE
epic: Refactor Inference logic from Server Logic

### ISSUE THREAD

**Issue by dan-jan** [janhq/cortex#516]
- Dynammic linking of "Inference Engines

**Comment by tikikun** [comment]
@vansangpfiev to research and estimate feasibility

**Comment by vansangpfiev** [comment]
I have created new repository for llamacpp backend https://github.com/janhq/llamacpp_cortex. Still need some [CI setup](https://github.com/janhq/llamacpp_cortex/issues/1) and [examples ](https://github.com/janhq/llamacpp_cortex/issues/2)to run llamacpp_cortex standalone.  
Basically, cortex_cpp will pull shared library from llamacpp_cortex repository, then load it to use.

**Comment by tikikun** [comment]
Posted here for more visibility

![Image](https://github.com/janhq/cortex/assets/22268502/024d899d-a39f-4485-afdf-8ef19c75137a)

**Comment by tikikun** [comment]
Issues for migration to the new design:
- Cameron:
- https://github.com/janhq/cortex/issues/534
- Sang:
- https://github.com/janhq/cortex/issues/535

**Comment by louis-jan** [comment]
It's done alrd @vansangpfiev
