### ISSUE TITLE
bug: weird responses from nitro when cache enabled

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex#526]
**Describe the bug**
Nitro seems to be broken when enabled cache. It spams nonsense text after some time.

**To Reproduce**
1. Load model with `caching_enabled` = true
2. Start conversation
3. Nitro responses with some nonsense texts

**Expected behavior**
Nitro responses nicely when cache enabled.

**Comment by tikikun** [comment]
Can you attach current fixing branch to this issue

**Comment by vansangpfiev** [comment]
Fixing branch is: https://github.com/janhq/nitro/pull/508
