### ISSUE TITLE
feat: Migration from coupled server to engine - Python Sub System

### ISSUE THREAD

**Issue by tikikun** [janhq/cortex#534]
**Problem**
Currently @CameronNg is working on Python sub system, but we are in the process of migrating to a more decoupled project.

@CameronNg needs to refactor it to a single component backend, first version is being implemented by @vansangpfiev 

**Success Criteria**
Run alongside with other backends like llama cpp etc, as an engine

**Comment by tikikun** [comment]
current PR

https://github.com/janhq/cortex/pull/505

**Comment by louis-jan** [comment]
It's now cortex.python-rt
