### ISSUE TITLE
feat: Migration from coupled server to engine - llamacpp

### ISSUE THREAD

**Issue by tikikun** [janhq/cortex#535]
**Problem**
Previously was coupled into nitro, now will be the first decoupled example for the team to follow, also possibly will be a template in itself to develop engine.

**Comment by vansangpfiev** [comment]
Split into sub-issues:
- https://github.com/janhq/cortex.llamacpp/issues/1
- https://github.com/janhq/cortex.llamacpp/issues/2
- https://github.com/janhq/cortex.llamacpp/issues/3
- https://github.com/janhq/cortex.llamacpp/issues/4

**Comment by louis-jan** [comment]
It's completed
