### ISSUE TITLE
feat: Support for multilingual embedding models and simultaneous hosting of LLM & embedding models

### ISSUE THREAD

**Issue by eckartal** [janhq/cortex#562]
**Problem**
Jan lacks support for multilingual embedding models and cannot host both LLM and embedding models simultaneously.

**Success Criteria**
Jan should be enhanced to support a broader range of multilingual embedding models. Plus, it should be capable of hosting both LLM and embedding models concurrently within a single system. 

**Additional context**

**Comment by louis-jan** [comment]
It is supported with the latest Cortex version; the Jan x Cortex would cover this.
