### ISSUE TITLE
feat: Multible Documents(PDF) for Embedding

### ISSUE THREAD

**Issue by kalle07** [janhq/cortex#567]
**Problem**
at the moment only talk with one document (ok two) but if the chat is closed the document must be every time i want use it,  again indexed and embeded

**Success Criteria**
so i want a library where i have maybe 20 books, i can seprate add or remove and they are permanently embedded.
so if i talk with one or two documents of these list , i only choose them, thats all.

**Additional context**
i have the assumption that documents bigger 100-200 pages are not embedded (10min nothing happend), smaller is ok ~30sec

**Comment by louis-jan** [comment]
UX Update needed? @imtuyethan

**Comment by ux-han** [comment]
Close as duplicated with https://github.com/janhq/jan/issues/2761
