### ISSUE TITLE
bug: Cannot able to build in windows

### ISSUE THREAD

**Issue by samsanan** [janhq/cortex#572]
I tried building cortex on windows from source and could able to build it
it fails with 
`make: *** No targets specified and no makefile found.  Stop.
`
**To Reproduce**
1. git clone https://github.com/janhq/cortex.git
2. open terminal, cd cortex
3. Build nitro_deps 
 cmake -S ./nitro_deps -B ./build_deps/nitro_deps
 cmake --build ./build_dep cmake ..s/nitro_deps --config Release
4. mkdir build && cd build
5. cmake ..
7.make -j $(%NUMBER_OF_PROCESSORS%)

**Expected behavior**
it should have build and nitro.exe should be present in the build folder

**Desktop (please complete the following information):**
 - OS: windows11 
 - Machine: HP VICTUS
 - intel i7 
 - 32gb ram

**Comment by louis-jan** [comment]
do you have Visual Studio C++ SDK setup yet? @samsanan, can do with Ninja or so as well

**Comment by louis-jan** [comment]
We will update Build From Source docs soon, could you please check this in the meanwhile? @samsanan 
https://github.com/janhq/cortex/blob/dev/.github/workflows/cortex-build.yml

**Comment by louis-jan** [comment]
Close due to env setup
