### ISSUE TITLE
Quickstart setup step 4 (not working)

### ISSUE THREAD

**Issue by zaynpatel** [janhq/cortex#595]
### Discussed in https://github.com/janhq/cortex/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **zaynpatel** December  4, 2023</sup>
I'm currently running the following command, copied from the documentation with the exception of a new localhost address:
```
url http://localhost:3000/inferences/llamacpp/loadmodel \
-H 'Content-Type: application/json' \
-d '{
    "llama_model_path": "/model/model/llama-2-7b-model.gguf",
    "ctx_len": 512,
    "ngl": 100
}'
```

I'm getting a 404 error which references that the `inferences/llamacpp/loadmodel` is not an available route. 
```
{"url":"/inferences/llamacpp/loadmodel","statusCode":404,"statusMessage":"Cannot find any route matching /inferences/llamacpp/loadmodel.","message":"Cannot find any route matching /inferences/llamacpp/loadmodel."}% 
```

I'm curious about how to proceed and wonder how I can test what other load model links might be correct?</div>

**Comment by fscardua** [comment]
Same problem here.

**Comment by 0xSage** [comment]
@zaynpatel , @fscardua sorry about this. Cortex is in private preview and has breaking changes daily. 

Can you both try the API playground: http://localhost:1337/api 
for easy curling?

**Comment by louis-jan** [comment]
The URL has been changed; now, Cortex will serve the chat/completions endpoint at http://localhost:3000/inferences/server/loadmodel.

**Comment by 0xSage** [comment]
closing as solved
