### ISSUE TITLE
feat: Cor‌‌tex Storage has File System Support with YAML

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#616]
## Storage

By default, Cortex CLI stores model binaries and thread history in `$(npm list -g @janhq/cortex)`
Within the `/lib/node_modules/@janhq/cortex/dist/` subdirectory.

**Success Criteria**
- [x] Changing storage location / mec‌hanis‌m: from using SQLite to storing the model data in a model.yml file
- [x] Additional database types like mysql or postgresql

**Additional context**

**Comment by louis-jan** [comment]
It's completed
