### ISSUE TITLE
bug: `cortex start -a` doesn't attach interactive shell

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#644]
1. cortex models start -a ...
2. no interactive shell, but model does start 

I also tried `cortex models start ID -a` and `cortex models start -a ID`

i.e. 
```sh

❯ cortex models start -a bartowski/Llama-3-8B-Instruct-Coder-v2-GGUF
{
  message: 'Model loaded successfully',
  modelId: 'bartowski/Llama-3-8B-Instruct-Coder-v2-GGUF'
}
❯ |
```

**Comment by louis-jan** [comment]
There is a limitation where Cortex was running; this would only work on a fresh start. Will sort it out soon.

**Comment by louis-jan** [comment]
Fixed
