### ISSUE TITLE
feat: Cortex has nightly builds?

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#646]
Similar to Jan, offer nightly builds for cortex.

Naming should include date, roughly: `nightly-date-os/cpu/gpu_info`

**Comment by 0xSage** [comment]
PLEEZE

**Comment by 0xSage** [comment]
@hiento09 can i check, cmiiw, we have nightly for cortex now right? Pls close if so.

**Comment by hiento09** [comment]
Hey @0xSage , yeah we have nightly build for cortex. However we are moving out cortex.llamacpp from cortex cpp, I will update the CICD later when we finish the migration

**Comment by 0xSage** [comment]
is the plan for each repo to have its own nightly?

i.e cortex, cortex.llama, etc.

**Comment by hiento09** [comment]
They already have, and be enable for a while, you can check it here @0xSage https://github.com/janhq/cortex.llamacpp/actions/workflows/nightly.yml => cortex.llamacpp
https://github.com/janhq/cortex/actions/workflows/nightly.yml => cortex
https://github.com/janhq/jan/actions/workflows/nightly-integrate-cortex-cpp.yml => Jan
