### ISSUE TITLE
Cortex should be able to start llama3 after confirming it was downloaded correctly

### ISSUE THREAD

**Issue by danidemi** [janhq/cortex#696]
**Describe the bug**
cortex confirm download of llama3 model but then fails to start it. 

**To Reproduce**
```powershell
PS> cortex pull llama3
Model already exists
PS> cortex models start llama3
{ message: 'Model failed to load', modelId: 'llama3' }
```

**Expected behavior**
Cortex should start the llama3 model after confirming it was correctly downloaded

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version downloaded 
 ```powershell
> npm -v -g @janhq/cortex
9.4.0
```

**Comment by Van-QA** [comment]
hi @danidemi, the command to download, and run the m‌odel would be:
`cortex run llama3`
Thank you
