### ISSUE TITLE
feat:  Cortex multiple engines onboarding

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#704]
**Problem**

**Success Criteria**

**Additional context**

**Comment by louis-jan** [comment]
Update: 
- As a new user, I can list all available engines with `cortex engines list`
<img width="1026" alt="image" src="https://github.com/janhq/cortex/assets/133622055/a8c7237a-bdf7-4442-bdcd-b8ff284ab23b">

- As a new user, I can install any engine with the engine name: `cortex engines init cortex.tensorrt-llm`
<img width="1026" alt="image" src="https://github.com/janhq/cortex/assets/133622055/f5190269-1ff4-4590-aedd-b2870824b329">

- When pulling or starting any model, if the engine is not initialized, it will be installed beforehand:
<img width="1026" alt="image" src="https://github.com/janhq/cortex/assets/133622055/cc0faded-b95e-4362-99ec-5b1a2c115d9e">

cc @gabrielle-ong @Van-QA
