### ISSUE TITLE
bug: Issues with cli on Linux and Mac

### ISSUE THREAD

**Issue by avb-is-me** [janhq/cortex#746]
Was able to globally install the CLI, and complete a pull, but found on both linux(Github codespaces 16GB) and Mac(Apple m2 8G),  ran into issues with `cortex models run llama3`.  When I ran the command it seemed like nothing happened.  Additionally serve would run successfully but when visited lead to a 404.

Looks Successful

<img width="628" alt="Screenshot 2024-06-20 at 11 38 52 PM" src="https://github.com/janhq/cortex/assets/104213687/82cebbed-3e56-4d43-b1ea-92e5b2ba50d6">

When visited:

<img width="788" alt="Screenshot 2024-06-20 at 11 39 45 PM" src="https://github.com/janhq/cortex/assets/104213687/1819ccae-463f-4eea-9372-7656aa535777">

**To Reproduce**

Steps to reproduce the behavior, follow these instructions:

### 1. Install Cortex using NPM
npm i -g @janhq/cortex

### 2. Download a GGUF model
cortex models pull llama3

### 3. Run the model to start chatting
cortex models run llama3

### 4. (Optional) Run Cortex in OpenAI-compatible server mode
cortex serve

**Expected behavior**
Success message or interaction on run {model}, and swagger ui on cortex serve

**Desktop (please complete the following information):**
 - OS: Linux, Mac

**Comment by l2D** [comment]
You should run the model with:

```sh
cortex models start <model_id>
```

and Swagger UI available at `http://${host}:${port}/api` e.g. `http://localhost:1337/api`

<details><summary>Screenshot</summary>
<p>

![20240622_0328PM_K1QAGndP@2x](https://github.com/janhq/cortex/assets/20911264/00b9b89e-7587-4c3c-97b1-b5f3d7ebc412)

</p>
</details>

**Comment by avb-is-me** [comment]
@louis-jan did you try on a github codespaces using linux?  Also I think try a fresh install, aka for users that haven't installed cortex yet or pulled a model
