### ISSUE TITLE
install_cortex-cpp has a few errors that block installation

### ISSUE THREAD

**Issue by dpkirchner** [janhq/cortex#750]
On line https://github.com/janhq/cortex/blob/f5e6b2f48f61c74e8a81fca11b4ea7bfe39580fa/cortex-cpp/install.sh#L57 the script fails if `/tmp/cortex-cpp.tar.gz` does not already exist (probably needs to be `rm -f`). On line https://github.com/janhq/cortex/blob/f5e6b2f48f61c74e8a81fca11b4ea7bfe39580fa/cortex-cpp/install.sh#L66 the script fails when `cp` tries to copy `engines` from the tarball (a directory). A possible fix is to add `-r`, however I'm not sure that is always going to be correct. It might make more sense to run `tar -C /usr/local/bin --strip=1 /tmp/cortex-cpp.tar.gz` instead of using the for loop.

**Comment by louis-jan** [comment]
The install.sh file has been deprecated.
