### ISSUE TITLE
bug: Outdated Quickstart Guide

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#753]
**Description**: 
The quickstart guide is outdated and the commands listed do not work.
`cortex models run`

**Reproduction Steps**: 
Follow the quickstart guide.

**Expected Behavior**: 
The commands should work as described in the guide

**Environment:**
Github codespace
4 cores 16gb RAM

https://discord.com/channels/1107178041848909847/1204617960615055401/1253826168520445996

**Comment by irfanpena** [comment]
Hi @Van-QA , the updated quickstart guide is in this PR: https://github.com/janhq/cortex-web/pull/43 but needs approval to merge. Kindly check thanks

**Comment by 0xSage** [comment]
@Van-QA yes this one should be in a different docs repo 🙏

**Comment by Van-QA** [comment]
hi @0xSage, actually, it's intentionally in cortex, so that all of them are in the same filter
