### ISSUE TITLE
bug: `cortex models` should == `cortex models -h`

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#754]
**Description**: 
Running the cortex models command does not return any response.`cortex models`

**Reproduction Steps**: 
1. Open a terminal.
2. Run `cortex models`.

**Expected Behavior**: 
The command should return a list of available models or an error message if the command is not available.

**Environment:**
Github codespace
4 cores 16gb RAM

![image](https://github.com/janhq/cortex/assets/64197333/9a45678b-5990-4ec8-934e-c3efac7f1b61)

https://discord.com/channels/1107178041848909847/1204617960615055401/1253826168520445996

**Request**
Ideally: all commands should bring up -h

i.e. 
For commands that would normal require args:
- [ ] `cortex presets` == `cortex presets -h`
- [ ] `embeddings` == `embeddings`
- [ ] `benchmark` ...
- [ ] `everything`

Not applicable to something like `cortex serve` which should jsut start the server...

**Comment by 0xSage** [comment]
@Van-QA I renamed the issue to be more specific. 

@louis-jan its up to you in terms of deciding if the short hand is for `list` or `-h`

I'm ok with either. 

Thanks for already updating `cortex` to be shorthand for `cortex -h`. Its helpful.
