### ISSUE TITLE
feat: better `cortex serve` CLI experience

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#755]
**Description**: 
Running `cortex serve` returns a 404 error but the error message is not helpful.

**Reproduction Steps**: 

1. Open a terminal. 
2. Run cortex serve.
3. Observe the error message

**Expected Behavior**: 
The error message should provide more information on why the command failed.

**Environment:**
Github codespace
4 cores 16gb RAM

https://discord.com/channels/1107178041848909847/1204617960615055401/1253826168520445996
![image](https://github.com/janhq/cortex/assets/64197333/0fdbbc1c-8044-47c1-badb-0870e0c883ce)

**Comment by 0xSage** [comment]
@Van-QA can you try to reproduce the conditions under which this might have happened?

**Comment by 0xSage** [comment]
Here's a rough spec for expected behavior: 
https://www.notion.so/jan-ai/cortex-serve-2f5293507b094d2abcdf1c0aa809d370?pvs=4

**Comment by louis-jan** [comment]
Updated: There are Playground URL printed out, also for the error information.
<img width="1026" alt="image" src="https://github.com/janhq/cortex/assets/133622055/9462f555-bb94-474e-bd16-ae4ad4c4b6c9">

<img width="1026" alt="image" src="https://github.com/janhq/cortex/assets/133622055/c4bd1bf6-73d9-4891-b545-59b1a1d4057d">

**Comment by louis-jan** [comment]
Regarding whether `cortex serve` should auto-start models, this is not relevant since it's more about smart routing. We allow users to pull and load multiple models at the same time. It's better to do this with certain requests instead of global serve

e.g.
https://github.com/janhq/cortex/issues/803
