### ISSUE TITLE
Cortex Model Hub Page (MVP version)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/cortex#764]
# Specs
https://www.notion.so/jan-ai/Cortex-Model-Hub-598e62bdc1d4472aaa8e1d5d80844b66?pvs=4

# Design
https://www.figma.com/design/WPcuxh4ngogYSwBvs8CTRF/Cortex-Website?node-id=0-1

![Image](https://github.com/janhq/cortex/assets/89722390/d17f0b33-2982-419d-9441-52d3e0d809ac)

**Comment by 0xSage** [comment]
Left a few nits, but largely lgtm!
