### ISSUE TITLE
feat: New cortex github banner image

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#766]
outdated visuals and style: ![image](https://github.com/janhq/cortex/assets/69952136/0fe17a60-ac0c-427f-8482-04235b45e5d6)

Can we do one using our new visual style (white background, bold)

And use the commands similar to what I wrote for : https://github.com/janhq/cortex-web/issues/47

**Comment by louis-jan** [comment]
Updated @imtuyethan
