### ISSUE TITLE
bug: Check for install requirements before downloading models

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#778]
1. Users will (often) just do `cortex run`
2. Model starts downloading
3. Takes forever 10mn+
4. Users is missing dependences like MPI, NVCC, etc.
5. Many errors. Huge explosion. No way to troubleshoot.
6. BUG: the model also doesn't seem to get saved in /models
7. Users have to install deps and redownload.
8. This is enough for most people to abandon cortex. 

Ideal flow. 

1. If users are using trt/onnx models for the first time, check for deps
2. If missing, guide users through the respective `init` process...

Question: 
1. Is there a way to check for deps efficiently? 
2. i.e. after users configure everything, maybe theres a flag or something. 
3. not sure - up for discussion

**Comment by louis-jan** [comment]
That's a critical issue, I'm trying to address this. Thank you @0xSage

**Comment by louis-jan** [comment]
This is addressed, MPI dependency is bundled with the engine by @vansangpfiev . Cuda version check is added by @marknguyen1302. There is a gate to check software & hardware compatibility before downloading model.
