### ISSUE TITLE
Cortex Benchmark

### ISSUE THREAD

**Issue by imtuyethan** [janhq/cortex#798]
# Specs
https://www.notion.so/jan-ai/Collect-User-Submitted-cortex-benchmark-data-1b10fe557e2745ff85473fd3cc227b12?pvs=4

Commands: 

```shell
cortex benchmark [model_id]
```

**Comment by louis-jan** [comment]
@marknguyen1302 to update: 
- What has been done? (e.g. cli commands)
- What is out of scope? (e.g. nested configuration params)
- What is in-progress/to-do? (e.g. docs)

**Comment by louis-jan** [comment]
This is implemented and can be closed; please feel free to open new issues for bug tracking.
