### ISSUE TITLE
bug: Resolve "Windows Firewall has blocked cortex.cpp"

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#799]
When we run Cortex for the first time, i.e. cortex run ..., a firewall warning "Windows firewall has blocked cortex.cpp" comes up. Anyway around this?

Related issue #627

**Comment by vansangpfiev** [comment]
Hi @0xSage, may I know which cortex version are you running?

**Comment by 0xSage** [comment]
it was the version as of July 26th

**Comment by vansangpfiev** [comment]
Thanks for your information. I will try to reproduce and fix the issue soon.

**Comment by hiento09** [comment]
@0xSage did you got this warning after running the `setup.exe` file on windows? https://github.com/janhq/cortex/issues/799

**Comment by louis-jan** [comment]
@hiento09 Let's create a new issue for installers. I think the mentioned issue is with the npm installation

**Comment by louis-jan** [comment]
@0xSage are you running tensorrt-llm model? there is a known issue related to MPI server

**Comment by ux-han** [comment]
![Screenshot 2024-08-28 at 10 29 35 PM](https://github.com/user-attachments/assets/9ffed3b9-bef4-4ec8-9461-260794e462f6)
