### ISSUE TITLE
epic: support tensorrt-llm batch manager

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex#828]
our research team uses batch size ~128 to generate synthetic data.

we should dogfood cortex for this.

add BM to cortex, so we can use our own software for training purposes.
https://nvidia.github.io/TensorRT-LLM/advanced/batch-manager.html

**Comment by vansangpfiev** [comment]
Related ticket: https://github.com/janhq/cortex.tensorrt-llm/issues/51
